module.exports = {
    MORALIS_APP_ID: process.env.MORALIS_APP_ID || '<MORALIS_APP_ID>',
    MORALIS_SERVER_URL: process.env.MORALIS_SERVER_URL || '<MORALIS_SERVER_ID>',
    CONTRACT_ADDRESS: process.env.CONTRACT_ADDRESS || '<SMART_CONTRACT_ADDRESS>'
}