module.exports = {
    MORALIS_APP_ID: process.env.REACT_APP_MORALIS_APP_ID || '<MORALIS_APP_ID>',
    MORALIS_SERVER_URL: process.env.REACT_APP_MORALIS_SERVER_URL || '<MORALIS_SERVER_ID>',
    CONTRACT_ADDRESS: process.env.REACT_APP_CONTRACT_ADDRESS || '<SMART_CONTRACT_ADDRESS>'
}